config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tickets
  mount Ckeditor::Engine => '/ckeditor'
  resources :roles
  resources :skills
  resources :designations
  resources :leafs
  resources :attendences do
    collection do
      get :update_attendence
    end
  end
  resources :salaries
  resources :daily_tasks
  get 'dashboard/index'
  root 'dashboard#index'
  resources :performances
  resources :holidays
  devise_for :employees
  resources :employees do
    collection do
      get :search
    end
  end

  namespace :hr do
    resources :monthly_salaries
    resources :employees do
      resources :leafs, only: :update do
        collection do
          get :index
        end
      end
    end

    resources :attendences
    get '/emp-attendance/:id', to: 'attendences#show_attendence', as: 'show_attendance'
    get '/search', to: 'attendences#search'
  end

  namespace :api do
    namespace :v1 do
      resources :leafs, only: %i[index create update]
      resources :attendences, only: %i[index show create update]
      resources :performances, only: [:index]
      resources :daily_tasks, only: %i[index show create update]
      resources :holidays, only: %i[index]
      resources :tickets, only: %i[index create]
      resources :dashboard, only: %i[index]
    end
  end

  namespace :admin_main do
    resources :holidays
    resources :tickets, only: %i[index show update] do
      resources :comments, only: [:create]
    end
    resources :employees
  end

  get '/set_ip', to: 'dashboard#set_ip'
  get '/profile', to: 'employees#profile'

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'Employee', at: 'auth'
      resources :employees, only: %i[show] do
        collection do
          put 'update_password'
        end
      end
    end
  end

  patch '/accept/:id', to: 'tickets#decline_ticket', as: 'decline_ticket'
end

app/models/holiday.rb
class Holiday < ApplicationRecord
	validates :holiday_name, presence: true
	validates :holiday_date, presence: true
	validates :holiday_type, presence: true
	enum holiday_type: [:National,:Optional]
						 
end

app/controllers/admin_main/holidays_controller.rb
# frozen_string_literal: true

module AdminMain
  class HolidaysController < ApplicationController
    include AdminHoliday

    before_action :set_holiday, only: %i[edit update destroy show]

    private

    def set_holiday
      @holiday = Holiday.find_by_id params[:id]
      redirect_to root_path, { notice: 'NOT FOUND' } unless @holiday.present?
    end
  end
end

app/controllers/api/v1/holidays_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class HolidaysController < ApplicationController
      before_action :authenticate_employee!
      skip_before_action :verify_authenticity_token

      def index
        holiday_data = Holiday.all
        render json: {
          data: serializer_data(holiday_data, holiday_serializer),
          status: 200
        }
      end

      private

      def holiday_serializer
        Api::V1::HolidaySerializer
      end
    end
  end
end

app/controllers/holidays_controller.rb
# frozen_string_literal: true

# Holidays controller
class HolidaysController < InheritedResources::Base
  before_action :authenticate_employee!
  load_and_authorize_resource
  include AdminHoliday
end

app/views/holidays/_form.html.erb
<h1 style="width: 300px;"></h1>

<%= form_with(model: @holiday) do |form| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>
      <ul>
        <% @holiday.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :holiday_name %>
    <%= form.text_field :holiday_name, class: 'form-control'%>
  </div>

  <div class="field mt-3 mb-3">
    <%= form.label :holiday_type %>
    <%= form.select :holiday_type, Holiday.holiday_types.keys, {}, class: 'form-control' %>
  </div>

  <div class="field mt-3 mb-3">
    <%= form.label :holiday_date %>
    <%= form.date_field :holiday_date, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
</aside><!-- End Sidebar-->

  <main id="main" class="main">
<h1>Editing Holiday</h1>
<div class="card shadow p-5">
    <div class="mb-3">
	<%= render 'form', holiday: @holiday %>

	<%= link_to 'Show', @holiday %> |
	<%= link_to 'Back', holidays_path %>
</div>
</div>
</main>

app/views/holidays/index.html.erb
</aside><!-- End Sidebar-->

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Holidays</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">Home</li>
          <li class="breadcrumb-item">Holiday</li>
          <li class="breadcrumb-item active">List</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        
        <div class="col-lg-12">

          <div class="card">
            <% if current_employee.is_hr? %>
              <div class="p-3">
                  <%= link_to 'Add Holiday', new_holiday_path, class: 'btn btn-primary'%>
              </div>
            <% end %>
            <div class="card-body">
             

              <!-- Table with stripped rows -->
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Holiday Name</th>
                    <th scope="col">Holiday Type</th>
                    <th scope="col">Date</th>
                  </tr>
                </thead>
                <tbody>
                  <% @holidays.each do |holiday| %>
                  <tr>
                    <th scope="row"><%= holiday.id %></th>
                    <td><%= holiday.holiday_name&.capitalize() %></td>
                     <td><%= holiday.holiday_type&.capitalize() %></td>
                    <td><%= holiday.holiday_date %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->

app/views/holidays/new.html.erb
</aside><!-- End Sidebar-->

  <main id="main" class="main">
  	<div class="card shadow p-5">
    <div class="mb-3">

		<%= render 'form'%>

		<%= link_to 'Back', holidays_path %>
	</div>
</div>
</main>

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Holiday name:</strong>
  <%= @holiday.holiday_name %>
</p>

<p>
  <strong>Holiday date:</strong>
  <%= @holiday.holiday_date %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> 
<%= link_to 'Back', holidays_path %>