config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tickets
  mount Ckeditor::Engine => '/ckeditor'
  resources :roles
  resources :skills
  resources :designations
  resources :leafs
  resources :attendences do
    collection do
      get :update_attendence
    end
  end
  resources :salaries
  resources :daily_tasks
  get 'dashboard/index'
  root 'dashboard#index'
  resources :performances
  resources :holidays
  devise_for :employees
  resources :employees do
    collection do
      get :search
    end
  end

  namespace :hr do
    resources :monthly_salaries
    resources :employees do
      resources :leafs, only: :update do
        collection do
          get :index
        end
      end
    end

    resources :attendences
    get '/emp-attendance/:id', to: 'attendences#show_attendence', as: 'show_attendance'
    get '/search', to: 'attendences#search'
  end

  namespace :api do
    namespace :v1 do
      resources :leafs, only: %i[index create update]
      resources :attendences, only: %i[index show create update]
      resources :performances, only: [:index]
      resources :daily_tasks, only: %i[index show create update]
      resources :holidays, only: %i[index]
      resources :tickets, only: %i[index create]
      resources :dashboard, only: %i[index]
    end
  end

  namespace :admin_main do
    resources :holidays
    resources :tickets, only: %i[index show update] do
      resources :comments, only: [:create]
    end
    resources :employees
  end

  get '/set_ip', to: 'dashboard#set_ip'
  get '/profile', to: 'employees#profile'

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'Employee', at: 'auth'
      resources :employees, only: %i[show] do
        collection do
          put 'update_password'
        end
      end
    end
  end

  patch '/accept/:id', to: 'tickets#decline_ticket', as: 'decline_ticket'
end

app/models/designation.rb
class Designation < ApplicationRecord
	has_one :employee, dependent: :destroy
end

app/controllers/designations_controller.rb
class DesignationsController < InheritedResources::Base
  before_action :authenticate_employee!
  load_and_authorize_resource
  private

    def designation_params
      params.require(:designation).permit(:name)
    end

end

app/views/designations/_form.html.erb
<%= form_with(model: designation) do |form| %>
  <% if designation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(designation.errors.count, "error") %> prohibited this designation from being saved:</h2>

      <ul>
        <% designation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/designations/edit.html.erb
<h1>Editing Designation</h1>

<%= render 'form', designation: @designation %>

<%= link_to 'Show', @designation %> |
<%= link_to 'Back', designations_path %>

app/views/designations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Designations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designations.each do |designation| %>
      <tr>
        <td><%= designation.name %></td>
        <td><%= link_to 'Show', designation %></td>
        <td><%= link_to 'Edit', edit_designation_path(designation) %></td>
        <td><%= link_to 'Destroy', designation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Designation', new_designation_path %>

app/views/designations/new.html.erb
<h1>New Designation</h1>

<%= render 'form', designation: @designation %>

<%= link_to 'Back', designations_path %>

app/views/designations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @designation.name %>
</p>

<%= link_to 'Edit', edit_designation_path(@designation) %> |
<%= link_to 'Back', designations_path %>