config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tickets
  mount Ckeditor::Engine => '/ckeditor'
  resources :roles
  resources :skills
  resources :designations
  resources :leafs
  resources :attendences do
    collection do
      get :update_attendence
    end
  end
  resources :salaries
  resources :daily_tasks
  get 'dashboard/index'
  root 'dashboard#index'
  resources :performances
  resources :holidays
  devise_for :employees
  resources :employees do
    collection do
      get :search
    end
  end

  namespace :hr do
    resources :monthly_salaries
    resources :employees do
      resources :leafs, only: :update do
        collection do
          get :index
        end
      end
    end

    resources :attendences
    get '/emp-attendance/:id', to: 'attendences#show_attendence', as: 'show_attendance'
    get '/search', to: 'attendences#search'
  end

  namespace :api do
    namespace :v1 do
      resources :leafs, only: %i[index create update]
      resources :attendences, only: %i[index show create update]
      resources :performances, only: [:index]
      resources :daily_tasks, only: %i[index show create update]
      resources :holidays, only: %i[index]
      resources :tickets, only: %i[index create]
      resources :dashboard, only: %i[index]
    end
  end

  namespace :admin_main do
    resources :holidays
    resources :tickets, only: %i[index show update] do
      resources :comments, only: [:create]
    end
    resources :employees
  end

  get '/set_ip', to: 'dashboard#set_ip'
  get '/profile', to: 'employees#profile'

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'Employee', at: 'auth'
      resources :employees, only: %i[show] do
        collection do
          put 'update_password'
        end
      end
    end
  end

  patch '/accept/:id', to: 'tickets#decline_ticket', as: 'decline_ticket'
end

app/views/shared/_admin_header.html.erb
<header id="header" class="header fixed-top d-flex align-items-center">
  <div class="d-flex align-items-center justify-content-between">
    <a href="" class="logo d-flex align-items-center">
      <h3 class="text-black">EMS</h3>
      <span class="d-none d-lg-block"></span>
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i>
  </div><!-- End Logo -->

  <div class="search-bar">
    <form class="search-form d-flex align-items-center" method="POST" action="#">
      <input type="text" name="query" placeholder="Search" title="Enter search keyword">
      <button type="submit" title="Search"><i class="fal fa-search"></i></button>
    </form>
  </div>

  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      <li class="nav-item d-block d-lg-none">
        <a class="nav-link nav-icon search-bar-toggle " href="#">
          <i class="bi bi-search"></i>
        </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-bell"></i>
          <span class="badge bg-primary badge-number">4</span>
        </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
          <i class="bi bi-chat-left-text"></i>
          <span class="badge bg-success badge-number">3</span>
        </a>
      </li>

      <li class="nav-item dropdown pe-3">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="/employees/" >
          <% unless current_employee.image.blank? %>
          <%= image_tag current_employee.image_url, class: "rounded-circle" %>
          <% end %>
          <span class="d-none d-md-block"><%= current_employee.email %></span>
        </a>
      </li>
    </ul>
  </nav>
</header>
<aside id="sidebar" class="sidebar">
  <ul class="sidebar-nav" id="sidebar-nav">
    <li class="nav-item">
    <%= link_to root_path, class: "nav-link collapsed a" do %> 
    <i class="bi bi-grid"></i>
    Dashboard
    <% end %>
  </li>

  <li class="nav-item">
    <% if current_employee.is_admin?  %>
    <%= link_to profile_path , class: "nav-link collapsed" do %>
    <i class="bi bi-person"></i>
    Profile
    <% end %>
    <% end %>
  </li>


  <li class="nav-item">
    <%= link_to admin_main_employees_path , class: "nav-link collapsed" do  %>
    <i class="bi bi-person"></i>
    <% unless current_employee.is_admin? %>
    Profile
    <% else %>
    Employees
    <% end %>
    <% end %>
 </li>

  <li class="nav-item">
    <%= link_to  performances_path, class: "nav-link collapsed" do %>
    <i class="bi bi-bar-chart"></i>
    Performance
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to  salaries_path, class: "nav-link collapsed" do %>
    <i class="bi bi-menu-button-wide"></i>
    Salary
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to  leafs_path, class: "nav-link collapsed" do %>
    <i class="bi bi-menu-button-wide"></i>
    Leave
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to  attendences_path, method: :get, class: "nav-link collapsed" do %>
    <i class="bi bi-menu-button-wide"></i>
    Attendence
    <% end %>
  </li>
  
  </li class="nav-item">
    <%= link_to  admin_main_holidays_path , class: "nav-link collapsed" do %>
    <i class="bi bi-menu-button-wide"></i>
    Holidays
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to  daily_tasks_path, class: "nav-link collapsed" do %>
    <i class="bi bi-menu-button-wide"></i>
    Daily Task
    <% end %>
  </li>
  
  <li class="nav-item">
    <%= link_to  admin_main_tickets_path, class: "nav-link collapsed" do %>
      <i class="bi bi-menu-button-wide"></i>
      Ticket
    <% end %>
  </li>

  <li class="nav-item">
    <%= link_to  destroy_employee_session_path, method: :delete, class: "nav-link collapsed" do %>
    <i class="bi bi-menu-button-wide"></i>
    Logout
    <% end %>
  </li>
</ul>
</aside>

app/views/shared/_footer.html.erb
<footer id="footer" class="text-center">
      
</footer><!-- End Footer -->

app/views/shared/_header.html.erb
 <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="" class="logo d-flex align-items-center">
        <h3 class="text-black">EMS</h3>
        <span class="d-none d-lg-block"></span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>

    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="fal fa-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->
      
        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-bell"></i>
            <span class="badge bg-primary badge-number">4</span>
          </a><!-- End Notification Icon -->

         

        </li><!-- End Notification Nav -->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-success badge-number">3</span>
          </a><!-- End Messages Icon -->

         

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="/employees/" >
            <% unless current_employee.image.blank? %>
              <%= image_tag current_employee.image_url, class: "rounded-circle" %>
            <% end %>
            <span class="d-none d-md-block"><%= current_employee.email %></span>
          </a><!-- End Profile Iamge Icon -->

          
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <%= link_to root_path, class: "nav-link collapsed a" do %> 
          <i class="bi bi-grid"></i>
          <%= "Dashboard" %>
        <% end %>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
          <% if current_employee.role.name == "HR" %>
          <%= link_to profile_path , class: "nav-link collapsed" do %>
          <i class="bi bi-person"></i>
              <%= 'Profile' %>
          <% end %>
          <% end %>
      </li>
      
      <li class="nav-item">
          <%= link_to employees_path , class: "nav-link collapsed" do %>
          <i class="bi bi-person"></i>
          <% unless current_employee.role.name == "HR" %>
              <%= 'Profile' %>
          <% else %>
              <%= 'Employees' %>
          <% end %>
          <% end %>
      </li>

      
      <li class="nav-item">
          <%= link_to  performances_path, class: "nav-link collapsed" do %>
          <i class="bi bi-bar-chart"></i>
          <%= 'Performance' %>
          <% end %>
      </li>
      <li class="nav-item">
          <%= link_to  salaries_path, class: "nav-link collapsed" do %>
          <i class="bi bi-menu-button-wide"></i>
          <%= 'Salary' %>
          <% end %>
      </li>
      <li class="nav-item">
          <% if current_employee.is_hr? %>
          <%= link_to hr_monthly_salaries_path , class: "nav-link collapsed" do %>
          <i class="bi bi-person"></i>
              <%= 'Monthly Salary' %>
          <% end %>
          <% end %>
      </li>
      <li class="nav-item">
          <%= link_to  leafs_path, class: "nav-link collapsed" do %>
          <i class="bi bi-menu-button-wide"></i>
          <%= 'Leave' %>
          <% end %>
      </li>
      <li class="nav-item">
        <%= link_to  attendences_path, method: :get, class: "nav-link collapsed" do %>
          <%#= link_to  attendences_path, method: :post, class: "nav-link collapsed" do %>
            <i class="bi bi-menu-button-wide"></i>
            <%= 'Attendence' %>
          <% end %>
        
      </li>
      </li class="nav-item">
          <%= link_to  holidays_path , class: "nav-link collapsed" do %>
          <i class="bi bi-menu-button-wide"></i>
          <%= 'Holidays' %>
          <% end %>
      </li>
      <li class="nav-item">
          <%= link_to  daily_tasks_path, class: "nav-link collapsed" do %>
          <i class="bi bi-menu-button-wide"></i>
          <%= 'Daily Task' %>
          <% end %>
      </li>
      <li class="nav-item">
          <%= link_to  tickets_path, class: "nav-link collapsed" do %>
          <i class="bi bi-menu-button-wide"></i>
          <%= 'Ticket' %>
          <% end %>
      </li>
      <li class="nav-item">
          <%= link_to  destroy_employee_session_path, method: :delete, class: "nav-link collapsed" do %>
          <i class="bi bi-menu-button-wide"></i>
          <%= 'Logout' %>
          <% end %>
      </li>
    </ul>
  </aside>