config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :tickets
  mount Ckeditor::Engine => '/ckeditor'
  resources :roles
  resources :skills
  resources :designations
  resources :leafs
  resources :attendences do
    collection do
      get :update_attendence
    end
  end
  resources :salaries
  resources :daily_tasks
  get 'dashboard/index'
  root 'dashboard#index'
  resources :performances
  resources :holidays
  devise_for :employees
  resources :employees do
    collection do
      get :search
    end
  end

  namespace :hr do
    resources :monthly_salaries
    resources :employees do
      resources :leafs, only: :update do
        collection do
          get :index
        end
      end
    end

    resources :attendences
    get '/emp-attendance/:id', to: 'attendences#show_attendence', as: 'show_attendance'
    get '/search', to: 'attendences#search'
  end

  namespace :api do
    namespace :v1 do
      resources :leafs, only: %i[index create update]
      resources :attendences, only: %i[index show create update]
      resources :performances, only: [:index]
      resources :daily_tasks, only: %i[index show create update]
      resources :holidays, only: %i[index]
      resources :tickets, only: %i[index create]
      resources :dashboard, only: %i[index]
    end
  end

  namespace :admin_main do
    resources :holidays
    resources :tickets, only: %i[index show update] do
      resources :comments, only: [:create]
    end
    resources :employees
  end

  get '/set_ip', to: 'dashboard#set_ip'
  get '/profile', to: 'employees#profile'

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'Employee', at: 'auth'
      resources :employees, only: %i[show] do
        collection do
          put 'update_password'
        end
      end
    end
  end

  patch '/accept/:id', to: 'tickets#decline_ticket', as: 'decline_ticket'
end

app/models/attendence.rb
class Attendence < ApplicationRecord
    self.inheritance_column = "not_sti"
    belongs_to :employee

    before_save :working_hour
    before_validation :checkout_time_validation,  on: [:update]

    private

    def working_hour
        unless self.checkout_time.nil?
            data = (self.checkout_time - self.checkin_time).to_i
            hour = (data/3600).to_i
            min = ((data-(hour*3600)) / 60).to_i
            sec = (data-(hour*3600) - (min*60)).to_i
            self.hour = "#{hour}:#{min}"
        end
    end

    def checkout_time_validation
        return errors.add :base, "Checkout time can't be blank"  unless checkout_time.present? 
       
        return errors.add :base, "Please select date #{checkin_time.strftime("%d-%m-%Y")} and time greater then #{checkin_time.strftime("%H:%M")} :)" unless checkin_time.strftime("%d") == checkout_time.strftime("%d") && checkout_time.strftime("%H:%M") > checkin_time.strftime("%H:%M")
    end


    def self.search(params)
        if params[:start_date].blank? && params[:end_date].blank?
            Attendence.all
        else
            Attendence.where(created_at: params[:start_date]..params[:end_date], employee_id: params[:id])
        end
    end
 
end

app/controllers/api/v1/attendences_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AttendencesController < ApplicationController
      before_action :authenticate_employee!
      before_action :set_attendance, only: %i[show]
      skip_before_action :verify_authenticity_token

      def index
        attendence_data = current_employee.attendences.order(created_at: :desc)
        render json: {
          data: serializer_data(attendence_data, attendence_serializer),
          message: ['daily attendence list '], status: 200, type: 'Success'
        }
      end

      def show
        # attendence_data = current_employee.attendences #Attendence.where(employee_id: attendence.employee_id)
        render json: {
          data: serializer_data(@attendence_data, attendence_serializer),
          message: ['show daily attendence  '], status: 302, type: 'Success'
        }
      end

      def create
        attendence_data = current_employee.attendences.where(checkin_time: Time.zone.now - 2.minutes..Time.zone.now,
                                                             employee_id: current_employee.id).last
        if attendence_data.nil?
          attendence_data = current_employee.attendences.create(employee_id: current_employee.id, checkin_time: Time.zone.now,
                                                                status: 'Present', checkin_ip_address: request.remote_ip)
        else
          attendence_data.update_column('checkout_time', nil)
        end
        render json: {
          data: serializer_data(attendence_data, attendence_serializer),
          message: ['successfully checkin '], status: 200, type: 'Success'
        }
      end

      def update
        attendence_data = current_employee.todays_last_attendence
        attendence_data.update(checkout_time: Time.zone.now, checkout_ip_address: request.remote_ip)
        render json: {
          data: serializer_data(attendence_data, attendence_serializer),
          message: ['successfully updated '], status: 200, type: 'Success'
        }
      end

      def set_attendance
        attendence = current_employee.attendences.find_by_id params[:id]
        return render json: { message: 'Not Found' }, status: 404 if attendence.nil?

        day = attendence.created_at
        @attendence_data = current_employee.attendences.where('created_at > ? AND created_at < ?', day.beginning_of_day,
                                                              day.end_of_day)
      end

      private

      def attendence_serializer
        Api::V1::AttendenceSerializer
      end
    end
  end
end

app/controllers/attendences_controller.rb
# frozen_string_literal: true

# Attendence controller
class AttendencesController < InheritedResources::Base
  # load_and_authorize_resource
  before_action :set_attendance, only: %i[show edit]
  def index
    @attendences = current_employee.attendences.order(created_at: :desc)
  end

  def show
    @attendences = Attendence.where(employee_id: @attendence.employee_id)
  end

  def create
    last_attendance = Attendence.where(checkin_time: Time.zone.now - 2.minutes..Time.zone.now,
                                       employee_id: current_employee.id).last
    if last_attendance.nil?
      Attendence.create(employee_id: current_employee.id, checkin_time: Time.zone.now,
                        status: 'Present', checkin_ip_address: request.remote_ip)
    else
      last_attendance.update_column('checkout_time', nil)
    end
    redirect_to root_path
  end

  def update_attendence
    attendence = current_employee.todays_last_attendence
    attendence.update(checkout_time: Time.zone.now, checkout_ip_address: request.remote_ip)
    redirect_to root_path
  end

  def set_attendance
    @attendence = current_employee.attendences.find_by_id params[:id]
    redirect_to root_path, alert: I18n.t('employee.not_found') unless @attendence.present?
  end
end

app/controllers/hr/attendences_controller.rb
# frozen_string_literal: true

# attendence controller
module Hr
  # attendence controller we are use for hr
  class AttendencesController < ApplicationController
    before_action :set_attendance, only: %i[show edit update]

    def show_attendence
      @employee = Employee.find(params[:id])
      employee_attendence(@employee.id)
    end

    def show
      employee_attendence(@attendence.employee_id)
    end

    def edit; end

    def update
      if params[:attendence].present?
        if @attendence.update(attendence_params)
          redirect_to hr_attendence_path
        else
          render :edit
        end
      else
        redirect_to hr_attendence_path
      end
    end

    def search
      @attendences = Attendence.search(params)
    end

    private

    def set_attendance
      @attendence = Attendence.find_by_id params[:id]
      redirect_to root_path, { notice: 'NOT FOUND :)' } unless @attendence.present?
    end

    def attendence_params
      params.require(:attendence).permit(:checkout_time)
    end

    def employee_attendence(employee_id)
      @attendences = Attendence.where(employee_id: employee_id)
    end
  end
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/views/attendences/_attendence.html.erb
<% array = [] %>
    <% @attendences.each do |attendence| %>
        <% unless array.include?(attendence.created_at.strftime('%d-%m-%y')) %>
            <% array << attendence.created_at.strftime('%d-%m-%y') %>
            <tr>
                <td><%= attendence.checkin_time&.strftime("%a %b %d %y %I:%M:%S %p") %></td>
                <td><%= attendence.checkout_time&.strftime("%a %b %d %y %I:%M:%S %p") %></td>
                <td><%= attendence.hour %></td>
                <% unless attendence.employee.is_hr? %>
                <td><%= link_to 'Edit', edit_hr_attendence_path(attendence), class: "btn btn-primary" %></td>
                <% end %>
                <td>
                    <% if current_employee.is_hr? %>
                    <%= link_to 'View', hr_attendence_path(attendence), class: "btn btn-primary" %>
                    <% else %>
                    <%= link_to 'View', attendence_path(attendence), class: "btn btn-primary" %>
                    <% end %>
                </td>
            </tr>
    <% end %>
<% end %>

app/views/attendences/_form.html.erb
</aside><!-- End Sidebar-->

  <main id="main" class="main">
<%= link_to 'Back', attendences_path, class: "btn btn-primary right mb-5"%>
<%= form_with(model: attendence, action: "edit") do |form| %>
  <% if attendence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendence.errors.count, "error") %> prohibited this attendence from being saved:</h2>

      <ul>
        <% attendence.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :checkout_time, class: "mb-3" %>
    <%= form.datetime_field :checkout_time, class: "form-control mb-3"%>
  </div>


  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

</main>

app/views/attendences/_search.html.erb
<% array = [] %>
    <% @attendences.each do |attendence| %>
                   <%# if current_employee.id == attendence.employee_id %>
        <% unless array.include?([attendence.created_at.strftime('%d-%m-%y'), attendence.employee_id]) %>
            <% array << [attendence.created_at.strftime('%d-%m-%y'), attendence.employee_id] %>
            <tr>
                <td><%= attendence.checkin_time&.strftime("%a %b %d %y %I:%M:%S %p") %></td>
                <td><%= attendence.checkout_time&.strftime("%a %b %d %y %I:%M:%S %p") %></td>
                <td><%= attendence.hour %></td>
                <% if current_employee.role.name == "HR" %>
                <td><%= attendence.employee.name %></td>
                <% end %>
                <td><%= link_to 'View', attendence_path(attendence), class: "btn btn-primary" %></td>
                <td><% if current_employee.role.name == "HR" %>
                    <% if attendence.employee.role.name == "HR" %>
                    <% else %>
                        <%= link_to 'Edit', edit_attendence_path(attendence), class: "btn btn-primary" %>
                    <% end %>
                <% end %></td>
            </tr>
        <% end %>
    <% end %>
                  <%# end %>

app/views/attendences/index.html.erb
</aside><!-- End Sidebar-->

  <main id="main" class="main">

    <div class="pagetitle">
      <h1 class="mb-4">Attendence List</h1>
    </div><!-- End Page Title -->
    <section class="section">
      <div class="row">
        
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
             <h5 class="card-title"></h5>
              <!-- Table with stripped rows -->
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">Checkin Time</th>
                    <th scope="col">Checkout Time</th>
                    <th scope="col">Working Hours</th>
                  </tr>
                </thead>
                <tbody class="search-data">
                 <%= render partial: "attendence", locals: { attendences: @attendences} %>
                </tbody>
              </table>
             
              <!-- End Table with stripped rows -->
            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->

app/views/attendences/search.js.erb
$(".search-data").html("<%= j render partial: "search" %>");

app/views/attendences/show.html.erb
</aside><!-- End Sidebar-->

  <main id="main" class="main">

    <div class="pagetitle">
      <h1 class="mb-4">Attendence List</h1>
    </div><!-- End Page Title -->
    <section class="section">
      <div class="row">
        
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
             

              <!-- Table with stripped rows -->
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">Checkin Time</th>
                    <th scope="col">Checkout Time</th>
                    <th scope="col">Working Hours</th>
                  </tr>
                </thead>
                <tbody>
                <%= link_to 'Back', :back,  class: "right btn btn-primary m-4" %>
                  <% @attendence %>
                  <% @attendences.each do |attendence| %>
                    <% if @attendence.created_at.strftime('%d-%m-%Y') == attendence.created_at.strftime('%d-%m-%Y') %>
                      <tr>
                        <td><%= attendence.checkin_time.strftime("%a %b %d %y %I:%M:%S %p") %></td>
                        <td><%= attendence.checkout_time&.strftime("%a %b %d %y %I:%M:%S %p") %></td>
                        <td><%= attendence.hour %></td>
                      </tr> 
                    <% end %> 
                  <% end %>
                </tbody>
              </table>
              <!-- End Table with stripped rows -->
            <%#= link_to 'Back', attendences_path, class: "right btn btn-primary" %>
            </div>
          </div>
         </div>
      </div>
    </section>

  </main><!-- End #main -->